name: CI
on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
